In [1]:
import pandas as pd
import numpy as np

In [2]:
from google.colab import files
uploaded = files.upload()

Saving supply_chain_inventory_dataset_15000_rows 2.xlsx to supply_chain_inventory_dataset_15000_rows 2.xlsx

In [3]:
df = pd.read_excel("supply_chain_inventory_dataset_15000_rows 2.xlsx")
df

,Product_ID,Product_Name,Category,Supplier_Name,Order_Date,Delivery_Date,Stock_Quantity,Reorder_Level,Units_Sold,Purchase_Cost,Selling_Price,Warehouse_Location,Shipping_Time_Days
0,PROD1000,Tablet,Fashion,Supplier D,2023-08-02,2023-08-07,3,59,241,1800,2081,Chennai,5
1,PROD1001,Tablet,Fashion,Supplier D,2024-04-11,2024-04-13,118,105,70,1950,2169,Hyderabad,2
2,PROD1002,Mixer,Sports,Supplier A,2024-08-16,2024-08-20,57,108,107,828,1322,Bangalore,4
3,PROD1003,TV,Sports,Supplier B,2024-11-30,2024-12-02,420,129,271,317,598,Chennai,2
4,PROD1004,Mixer,Fashion,Supplier C,2024-08-03,2024-08-11,401,77,210,645,1061,Mumbai,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,PROD15995,Shoes,Fashion,Supplier E,2024-03-03,2024-03-08,173,117,88,1917,2346,Delhi,5
14996,PROD15996,TV,Fashion,Supplier D,2023-06-22,2023-06-28,321,129,70,379,478,Hyderabad,6
14997,PROD15997,Tablet,Electronics,Supplier D,2024-06-22,2024-06-27,366,82,88,1080,1358,Hyderabad,5
14998,PROD15998,Camera,Electronics,Supplier D,2024-10-06,2024-10-11,25,65,180,521,720,Chennai,5
14999,PROD15999,Tablet,Sports,Supplier C,2023-05-02,2023-05-03,444,143,113,1000,1234,Bangalore,1

In [4]:
df.shape

(15000, 13)

In [5]:
df.describe()

,Order_Date,Delivery_Date,Stock_Quantity,Reorder_Level,Units_Sold,Purchase_Cost,Selling_Price,Shipping_Time_Days
count,15000,15000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000
mean,2023-12-28 15:20:09.600000,2024-01-03 03:14:35.520000,250.917933,99.802467,148.167200,1102.676733,1378.474133,5.496133
min,2023-01-01 00:00:00,2023-01-02 00:00:00,0.000000,50.000000,0.000000,200.000000,263.000000,1.000000
25%,2023-06-26 00:00:00,2023-07-02 00:00:00,126.000000,74.000000,72.000000,641.000000,918.000000,3.000000
50%,2023-12-26 00:00:00,2023-12-31 00:00:00,251.000000,100.000000,146.000000,1102.000000,1374.000000,6.000000
75%,2024-07-01 00:00:00,2024-07-07 00:00:00,375.000000,126.000000,224.000000,1560.000000,1836.000000,8.000000
max,2024-12-31 00:00:00,2025-01-10 00:00:00,500.000000,150.000000,300.000000,2000.000000,2492.000000,10.000000
std,NaN,NaN,144.554751,29.406247,86.652443,525.703573,541.562695,2.885690

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Product_ID          15000 non-null  object
 1   Product_Name        15000 non-null  object
 2   Category            15000 non-null  object
 3   Supplier_Name       15000 non-null  object
 4   Order_Date          15000 non-null  datetime64[ns]
 5   Delivery_Date       15000 non-null  datetime64[ns]
 6   Stock_Quantity      15000 non-null  int64
 7   Reorder_Level       15000 non-null  int64
 8   Units_Sold          15000 non-null  int64
 9   Purchase_Cost       15000 non-null  int64
 10  Selling_Price       15000 non-null  int64
 11  Warehouse_Location  15000 non-null  object
 12  Shipping_Time_Days  15000 non-null  int64
dtypes: datetime64[ns](2), int64(6), object(5)
memory usage: 1.5+ MB

No Null Values

In [7]:
df.isnull().sum()

Product_ID            0
Product_Name          0
Category              0
Supplier_Name         0
Order_Date            0
Delivery_Date         0
Stock_Quantity        0
Reorder_Level         0
Units_Sold            0
Purchase_Cost         0
Selling_Price         0
Warehouse_Location    0
Shipping_Time_Days    0
dtype: int64

No Duplicates

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
np.dtype(df['Delivery_Date'])

dtype('<M8[ns]')

In [10]:
np.dtype(df['Order_Date'])

dtype('<M8[ns]')

dtype('int64')

Ensure numeric columns are properly formatted

In [14]:
numerical_cols = ["Stock_Quantity","Reorder_Level","Units_Sold","Purchase_Cost","Selling_Price","Shipping_Time_Days"]
for col in numerical_cols:
  df[col] = pd.to_numeric(df[col], errors='coerce')

In [16]:
df[df["Stock_Quantity"] < 0]

Empty DataFrame
Columns: [Product_ID, Product_Name, Category, Supplier_Name, Order_Date, Delivery_Date, Stock_Quantity, Reorder_Level, Units_Sold, Purchase_Cost, Selling_Price, Warehouse_Location, Shipping_Time_Days]
Index: []

No negative or incorrect stock values

In [17]:
df.to_excel("cleaned_data_set.xlsx",index = False)
print("Data Cleaning Completed")

Data Cleaning Completed

In [18]:
from google.colab import files
files.download("cleaned_data_set.xlsx")